In [ ]:
import numpy as np
import pandas as pd
import psutil
import os
import matplotlib.pyplot as plt


time: 3.26 ms (started: 2022-12-11 22:35:35 +00:00)


In [ ]:
!pip install ipython-autotime

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
time: 6.58 s (started: 2022-12-11 22:35:36 +00:00)


In [ ]:
%load_ext autotime

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 6.17 ms (started: 2022-12-11 22:35:42 +00:00)


In [ ]:
data = pd.read_csv('Churn_Modelling.csv')

data.head(4)
data.info()
data.describe()
data.tail()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

time: 281 ms (started: 2022-12-11 22:35:42 +00:00)


In [ ]:
data = data.drop(['CustomerId', 'Surname', 'RowNumber'], axis = 1)



print(data.columns)
data.shape

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')


(10000, 11)

time: 26.3 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
x = data.iloc[:,0:10]
y = data.iloc[:,10]

print(x.shape)
print(y.shape)

print(x.columns)

(10000, 10)
(10000,)
Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')
time: 20.7 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
x = pd.get_dummies(x)

x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88                 1                  0   
1               1        112542.58                 0                  0   
2               0        113931.57                 1                  0   
3               0         93826.63                 1                  0   
4               1         79084.10                 0                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                1              1            0  
2                0              1            0  
3                0              1            0  
4                1              1            0

time: 73.8 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:

x.shape

(10000, 13)

time: 6.68 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(7500, 13)
(7500,)
(2500, 13)
(2500,)
time: 58.2 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

x_train = pd.DataFrame(x_train)
x_train.head()

0         1         2         3         4         5         6   \
0 -0.735507  0.015266  0.008860  0.673160  2.535034 -1.553624 -1.034460   
1  1.024427 -0.652609  0.008860 -1.207724  0.804242  0.643657 -1.034460   
2  0.808295 -0.461788  1.393293 -0.356937  0.804242  0.643657  0.966688   
3  0.396614 -0.080145  0.008860 -0.009356 -0.926551  0.643657  0.966688   
4 -0.467915  1.255605  0.701077 -1.207724  0.804242  0.643657  0.966688   

         7         8         9         10        11        12  
0 -1.640810 -1.015588  1.760216 -0.574682  1.087261 -1.087261  
1 -0.079272  0.984651 -0.568112 -0.574682  1.087261 -1.087261  
2 -0.996840 -1.015588 -0.568112  1.740094  1.087261 -1.087261  
3 -1.591746 -1.015588 -0.568112  1.740094 -0.919743  0.919743  
4  1.283302  0.984651 -0.568112 -0.574682 -0.919743  0.919743

time: 48.5 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
#Decision Tree Induction
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

model = DecisionTreeClassifier() 
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("The Training Accuracy of Decision Tree Model :", model.score(x_train, y_train))
print("The Testing Accuaracy of Decision Tree Model :", model.score(x_test, y_test))

cm = confusion_matrix(y_test, y_pred)
print(cm)

The Training Accuracy of Decision Tree Model : 1.0
The Testing Accuaracy of Decision Tree Model : 0.7996
[[1714  277]
 [ 224  285]]
time: 372 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
#Calculating Memory used
process = psutil.Process(os.getpid())
print("Total Used Memory for Decision Tree: ", end='')
print(process.memory_info().rss)


Total Used Memory for Decision Tree: 215203840
time: 3.3 ms (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
#SVM Model

from sklearn.svm import SVC

model = SVC()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("The Training Accuracy Of SVM Model :", model.score(x_train, y_train))
print("The Testing Accuracy of SVM Model :", model.score(x_test, y_test))

cm = confusion_matrix(y_test, y_pred)
print(cm)

The Training Accuracy Of SVM Model : 0.8625333333333334
The Testing Accuracy of SVM Model : 0.8616
[[1951   40]
 [ 306  203]]
time: 7.44 s (started: 2022-12-11 22:35:43 +00:00)


In [ ]:
process = psutil.Process(os.getpid())
print("Total Used Memory for SVM: ", end='')
print(process.memory_info().rss)

Total Used Memory for SVM: 316538880
time: 10.4 ms (started: 2022-12-11 22:35:51 +00:00)


In [ ]:
#ANN
import keras
from keras.models import Sequential
from keras.layers import Dense

time: 7.12 s (started: 2022-12-11 22:35:51 +00:00)


In [ ]:
# creating the model
model = Sequential()

# first hidden layer
model.add(Dense(units=6, activation = 'relu')) #input/first hidden layer
model.add(Dense(units=6, activation = 'relu')) #second hidden layer
model.add(Dense(units=1, activation = 'sigmoid')) #output layer

# Compiling the NN

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 

model.fit(x_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50
750/750 [==============================] - 4s 3ms/step - loss: 0.5801 - accuracy: 0.7116
Epoch 2/50
750/750 [==============================] - 1s 2ms/step - loss: 0.4368 - accuracy: 0.7996
Epoch 3/50
750/750 [==============================] - 1s 2ms/step - loss: 0.4257 - accuracy: 0.8056
Epoch 4/50
750/750 [==============================] - 1s 2ms/step - loss: 0.4171 - accuracy: 0.8127
Epoch 5/50
750/750 [==============================] - 1s 2ms/step - loss: 0.4027 - accuracy: 0.8259
Epoch 6/50
750/750 [==============================] - 1s 2ms/step - loss: 0.3845 - accuracy: 0.8387
Epoch 7/50
750/750 [==============================] - 1s 2ms/step - loss: 0.3700 - accuracy: 0.8467
Epoch 8/50
750/750 [==============================] - 1s 2ms/step - loss: 0.3620 - accuracy: 0.8492
Epoch 9/50
750/750 [==============================] - 1s 2ms/step - loss: 0.3580 - accuracy: 0.8525
Epoch 10/50
750/750 [==============================] - 1s 2ms/step - loss: 0.3550 - accuracy: 0.8520

time: 1min 23s (started: 2022-12-11 22:35:58 +00:00)


In [ ]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)

79/79 [==============================] - 0s 1ms/step
time: 283 ms (started: 2022-12-11 22:37:22 +00:00)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("The accuracy of ANN",(accuracy_score(y_test,y_pred))*100,"%")



[[1925   66]
 [ 272  237]]
The accuracy of ANN 86.48 %
time: 23.2 ms (started: 2022-12-11 22:38:49 +00:00)


In [ ]:
process = psutil.Process(os.getpid())
print("Total Used Memory for ANN: ", end='')
print(process.memory_info().rss)

Total Used Memory for ANN: 636325888
time: 3.7 ms (started: 2022-12-11 22:38:52 +00:00)
